const countryArr = [ 
  {"name": "Afghanistan", "country" : "AFG" , "currency" : "AFN" , "dialCode" : "+93", "decimal" : 2 }, 
  {"name": "Åland Islands", "country": "ALA" , "currency" : "EUR" , "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Albania", "country": "ALB", "currency" : "ALL" , "dialCode" : "+355", "decimal" : 2 }, 
  {"name": "Algeria", "country": "DZA", "currency" : "DZD" , "dialCode" : "+213", "decimal" : 2 }, 
  {"name": "American Samoa", "country": "ASM", "currency" : "USD" , "dialCode" : "+1684", "decimal" : 2 }, 
  {"name": "AndorrA", "country": "AND", "currency" : "EUR" , "dialCode" : "+376", "decimal" : 2 }, 
  {"name": "Angola", "country": "AGO", "currency" : "AOA" , "dialCode" : "+244", "decimal" : 2 },
  {"name": "Anguilla", "country": "AIA", "currency" : "NIL", "dialCode" : "+1264", "decimal" : 2 }, 
  {"name": "Antarctica", "country": "ATA", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Antigua and Barbuda", "country": "ATG", "currency" : "XCD", "dialCode" : "+1268", "decimal" : 2 }, 
  {"name": "Argentina", "country": "ARG", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Armenia", "country": "ARM", "currency" : "AMD", "dialCode" : "+374", "decimal" : 2 }, 
  {"name": "Aruba", "country": "ABW", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Australia", "country": "AUS", "currency" : "AUD", "dialCode" : "+61", "decimal" : 2 }, 
  {"name": "Austria", "country": "AUT", "currency" : "EUR" , "dialCode" : "+43", "decimal" : 2 }, 
  {"name": "Azerbaijan", "country": "AZE", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Bahamas", "country": "BHS", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Bahrain", "country": "BHR", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Bangladesh", "country": "BGD", "currency" : "BDT", "dialCode" : "+880", "decimal" : 2 }, 
  {"name": "Barbados", "country": "BRB", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Belarus", "country": "BLR", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Belgium", "country": "BEL", "currency" : "EUR" , "dialCode" : "+32", "decimal" : 2 }, 
  {"name": "Belize", "country": "BLZ", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Benin", "country": "BEN", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Bermuda", "country": "BMU", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Bhutan", "country": "BTN", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Bolivia", "country": "BOL", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Bosnia and Herzegovina", "country": "BIH", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Botswana", "country": "BWA", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Bouvet Island", "country": "BVT", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Brazil", "country": "BRA", "currency" : "BRL", "dialCode" : "+55", "decimal" : 2 }, 
  {"name": "British Indian Ocean Territory", "country": "IOT", "currency" : "USD" , "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Brunei Darussalam", "country": "BRN", "currency" : "BND", "dialCode" : "+673", "decimal" : 2 }, 
  {"name": "Bulgaria", "country": "BGR", "currency" : "BGN", "dialCode" : "+359", "decimal" : 2 }, 
  {"name": "Burkina Faso", "country": "BFA", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Burundi", "country": "BDI", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Cambodia", "country": "KHM", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Cameroon", "country": "CMR", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Canada", "country": "CAN", "currency" : "CAD", "dialCode" : "+1", "decimal" : 2 }, 
  {"name": "Cabo Verde", "country": "CPV", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Cayman Islands", "country": "CYM", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Central African Republic", "country": "CAF", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Chad", "country": "TCD", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Chile", "country": "CHL", "currency" : "CLP", "dialCode" : "+56", "decimal" : 0 }, 
  {"name": "China", "country": "CHN", "currency" : "CNY", "dialCode" : "+86", "decimal" : 2 }, 
  {"name": "Christmas Island", "country": "CXR", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Cocos (Keeling) Islands", "country": "CCK", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Colombia", "country": "COL", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Comoros", "country": "COM", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Congo", "country": "COG", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Congo, The Democratic Republic of the", "country": "COD", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Cook Islands", "country": "COK", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Costa Rica", "country": "CRI", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Cote D\"Ivoire", "country": "CIV", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Croatia", "country": "HRV", "currency" : "HRK", "dialCode" : "+385", "decimal" : 2 }, 
  {"name": "Cuba", "country": "CUB", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Cyprus", "country": "CYP", "currency" : "EUR" , "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Czech Republic", "country": "CZE", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Denmark", "country": "DNK", "currency" : "DKK", "dialCode" : "+45", "decimal" : 2 }, 
  {"name": "Djibouti", "country": "DJI", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Dominica", "country": "DMA", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Dominican Republic", "country": "DOM", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Ecuador", "country": "ECU", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Egypt", "country": "EGY", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "El Salvador", "country": "SLV", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Equatorial Guinea", "country": "GNQ", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Eritrea", "country": "ERI", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Estonia", "country": "EST", "currency" : "EUR" , "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Ethiopia", "country": "ETH", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Falkland Islands (Malvinas)", "country": "FLK", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Faroe Islands", "country": "FRO", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Fiji", "country": "FJI", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Finland", "country": "FIN", "currency" : "EUR" , "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "France", "country": "FRA", "currency" : "EUR" , "dialCode" : "+33", "decimal" : 2 }, 
  {"name": "French Guiana", "country": "GUF", "currency" : "EUR" , "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "French Polynesia", "country": "PYF", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "French Southern Territories", "country": "ATF", "currency" : "EUR" , "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Gabon", "country": "GAB", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Gambia", "country": "GMB", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Georgia", "country": "GEO", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Germany", "country": "DEU", "currency" : "EUR" , "dialCode" : "+49", "decimal" : 2 }, 
  {"name": "Ghana", "country": "GHA", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Gibraltar", "country": "GIB", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Greece", "country": "GRC", "currency" : "EUR" , "dialCode" : "+30", "decimal" : 2 }, 
  {"name": "Greenland", "country": "GRL", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Grenada", "country": "GRD", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Guadeloupe", "country": "GLP", "currency" : "EUR" , "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Guam", "country": "GUM", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Guatemala", "country": "GTM", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Guernsey", "country": "GGY", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Guinea", "country": "GIN", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Guinea-Bissau", "country": "GNB", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Guyana", "country": "GUY", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Haiti", "country": "HTI", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Heard Island and Mcdonald Islands", "country": "HMD", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Holy See (Vatican City State)", "country": "VAT", "currency" : "EUR" , "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Honduras", "country": "HND", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Hong Kong", "country": "HKG", "currency" : "HKD", "dialCode" : "+852", "decimal" : 2 }, 
  {"name": "Hungary", "country": "HUN", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Iceland", "country": "ISL", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "India", "country": "IND", "currency" : "INR" , "dialCode" : "+91", "decimal" : 2 }, 
  {"name": "Indonesia", "country": "IDN", "currency" : "IDR" , "dialCode" : "+62", "decimal" : 0 }, 
  {"name": "Iran, Islamic Republic Of", "country": "IRN", "currency" : "IRR", "dialCode" : "+98", "decimal" : 2 }, 
  {"name": "Iraq", "country": "IRQ", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Ireland", "country": "IRL", "currency" : "EUR" , "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Isle of Man", "country": "IMN", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Israel", "country": "ISR", "currency" : "ILS", "dialCode" : "+972", "decimal" : 2 }, 
  {"name": "Italy", "country": "ITA", "currency" : "EUR" , "dialCode" : "+39", "decimal" : 2 }, 
  {"name": "Jamaica", "country": "JAM", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Japan", "country": "JPN", "currency" : "JPY" , "dialCode" : "+81", "decimal" : 0 }, 
  {"name": "Jersey", "country": "JEY", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Jordan", "country": "JOR", "currency" : "JOD", "dialCode" : "+962", "decimal" : 3 }, 
  {"name": "Kazakhstan", "country": "KAZ", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Kenya", "country": "KEN", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Kiribati", "country": "KIR", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Korea, Democratic People\"S Republic of", "country": "PRK", "currency" : "KPW" , "dialCode" : "+850", "decimal" : 2 }, 
  {"name": "Korea, Republic of", "country": "KOR", "currency" : "KRW" , "dialCode" : "+82", "decimal" : 0 }, 
  {"name": "Kuwait", "country": "KWT", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Kyrgyzstan", "country": "KGZ", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Lao People\"S Democratic Republic", "country": "LAO", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Latvia", "country": "LVA", "currency" : "EUR" , "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Lebanon", "country": "LBN", "currency" : "LBP", "dialCode" : "+961", "decimal" : 2 }, 
  {"name": "Lesotho", "country": "LSO", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Liberia", "country": "LBR", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Libyan Arab Jamahiriya", "country": "LBY", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Liechtenstein", "country": "LIE", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Lithuania", "country": "LTU", "currency" : "EUR" , "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Luxembourg", "country": "LUX", "currency" : "EUR" , "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Macao", "country": "MAC", "currency" : "MOP", "dialCode" : "+853", "decimal" : 2 }, 
  {"name": "Macedonia, The Former Yugoslav Republic of", "country": "MKD", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Madagascar", "country": "MDG", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Malawi", "country": "MWI", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Malaysia", "country": "MYS", "currency" : "MYR" , "dialCode" : "+60", "decimal" : 2 }, 
  {"name": "Maldives", "country": "MDV", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Mali", "country": "MLI", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Malta", "country": "MLT", "currency" : "EUR" , "dialCode" : "+356", "decimal" : 2 }, 
  {"name": "Marshall Islands", "country": "MHL", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Martinique", "country": "MTQ", "currency" : "EUR" , "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Mauritania", "country": "MRT", "currency" : "EUR" , "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Mauritius", "country": "MUS", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Mayotte", "country": "MYT", "currency" : "EUR" , "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Mexico", "country": "MEX", "currency" : "MXN", "dialCode" : "+52", "decimal" : 2 }, 
  {"name": "Micronesia, Federated States of", "country": "FSM", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Moldova, Republic of", "country": "MDA", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Monaco", "country": "MCO", "currency" : "EUR" , "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Mongolia", "country": "MNG", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Montenegro", "country": "MNE", "currency" : "EUR" , "dialCode" : "NIL", "decimal" : 2 },
  {"name": "Montserrat", "country": "MSR", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 },
  {"name": "Morocco", "country": "MAR", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Mozambique", "country": "MOZ", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Myanmar", "country": "MMR", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Namibia", "country": "NAM", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Nauru", "country": "NRU", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Nepal", "country": "NPL", "currency" : "NPR", "dialCode" : "+977", "decimal" : 2 }, 
  {"name": "Netherlands", "country": "NLD", "currency" : "EUR" , "dialCode" : "+31", "decimal" : 2 }, 
  {"name": "New Caledonia", "country": "NCL", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "New Zealand", "country": "NZL", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Nicaragua", "country": "NIC", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Niger", "country": "NER", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Nigeria", "country": "NGA", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Niue", "country": "NIU", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Norfolk Island", "country": "NFK", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Northern Mariana Islands", "country": "MNP", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Norway", "country": "NOR", "currency" : "NOK", "dialCode" : "+47", "decimal" : 2 }, 
  {"name": "Oman", "country": "OMN", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Pakistan", "country": "PAK", "currency" : "PKR", "dialCode" : "+92", "decimal" : 2 }, 
  {"name": "Palau", "country": "PLW", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Palestinian Territory, Occupied", "country": "PSE", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Panama", "country": "PAN", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Papua New Guinea", "country": "PNG", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Paraguay", "country": "PRY", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Peru", "country": "PER", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Philippines", "country": "PHL", "currency" : "PHP", "dialCode" : "+63", "decimal" : 2 }, 
  {"name": "Pitcairn", "country": "PCN", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Poland", "country": "POL", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Portugal", "country": "PRT", "currency" : "EUR" , "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Puerto Rico", "country": "PRI", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Qatar", "country": "QAT", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Reunion", "country": "REU", "currency" : "Euro" , "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Romania", "country": "ROU", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Russian Federation", "country": "RUS", "currency" : "RUB", "dialCode" : "+7", "decimal" : 2 }, 
  {"name": "RWANDA", "country": "RWA", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Saint Helena", "country": "SHN", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Saint Kitts and Nevis", "country": "KNA", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Saint Lucia", "country": "LCA", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Saint Pierre and Miquelon", "country": "SPM", "currency" : "EUR" , "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Saint Vincent and the Grenadines", "country": "VCT", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Samoa", "country": "WSM", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "San Marino", "country": "SMR", "currency" : "EUR" , "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Sao Tome and Principe", "country": "STP", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Saudi Arabia", "country": "SAU", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Senegal", "country": "SEN", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Serbia", "country": "SRB", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Seychelles", "country": "SYC", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Sierra Leone", "country": "SLE", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Singapore", "country": "SGP", "currency" : "SGD" , "dialCode" : "+65", "decimal" : 2 }, 
  {"name": "Slovakia", "country": "SVK", "currency" : "EUR" , "dialCode" : "+421", "decimal" : 2 }, 
  {"name": "Slovenia", "country": "SVN", "currency" : "EUR" , "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Solomon Islands", "country": "SLB", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Somalia", "country": "SOM", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "South Africa", "country": "ZAF", "currency" : "ZAR", "dialCode" : "+27", "decimal" : 2 }, 
  {"name": "South Georgia and the South Sandwich Islands", "country": "SGS", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Spain", "country": "ESP", "currency" : "EUR" , "dialCode" : "+34", "decimal" : 2 }, 
  {"name": "Sri Lanka", "country": "LKA", "currency" : "LKR", "dialCode" : "+94", "decimal" : 2 }, 
  {"name": "Sudan", "country": "SDN", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Suriname", "country": "SUR", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Svalbard and Jan Mayen", "country": "SJM", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Swaziland", "country": "SWZ", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Sweden", "country": "SWE", "currency" : "SEK", "dialCode" : "+46", "decimal" : 2 }, 
  {"name": "Switzerland", "country": "CHE", "currency" : "CHF", "dialCode" : "+41", "decimal" : 2 }, 
  {"name": "Syrian Arab Republic", "country": "SYR", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Taiwan, Province of China", "country": "TWN", "currency" : "TWD", "dialCode" : "+886", "decimal" : 2 }, 
  {"name": "Tajikistan", "country": "TJK", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Tanzania, United Republic of", "country": "TZA", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Thailand", "country": "THA", "currency" : "THB", "dialCode" : "+66", "decimal" : 2 }, 
  {"name": "Timor-Leste", "country": "TLS", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Togo", "country": "TGO", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Tokelau", "country": "TKL", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Tonga", "country": "TON", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Trinidad and Tobago", "country": "TTO", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Tunisia", "country": "TUN", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Turkey", "country": "TUR", "currency" : "TRY", "dialCode" : "+90", "decimal" : 2 }, 
  {"name": "Turkmenistan", "country": "TKM", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Turks and Caicos Islands", "country": "TCA", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Tuvalu", "country": "TUV", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Uganda", "country": "UGA", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Ukraine", "country": "UKR", "currency" : "UAH", "dialCode" : "+380", "decimal" : 2 }, 
  {"name": "United Arab Emirates", "country": "ARE", "currency" : "AED", "dialCode" : "+971", "decimal" : 2 }, 
  {"name": "United Kingdom", "country": "GBR", "currency" : "GBP", "dialCode" : "+44", "decimal" : 2 }, 
  {"name": "United States", "country": "USA", "currency" : "USD" , "dialCode" : "+1", "decimal" : 2 }, 
  {"name": "United States Minor Outlying Islands", "country": "UMI", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Uruguay", "country": "URY", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Uzbekistan", "country": "UZB", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Vanuatu", "country": "VUT", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Venezuela", "country": "VEN", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Vietnam", "country": "VNM", "currency" : "VND", "dialCode" : "+84", "decimal" : 0 }, 
  {"name": "Virgin Islands, British", "country": "VGB", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Virgin Islands, U.S.", "country": "VIR", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Wallis and Futuna", "country": "WLF", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Western Sahara", "country": "ESH", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Yemen", "country": "YEM", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Zambia", "country": "ZMB", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2 }, 
  {"name": "Zimbabwe", "country": "ZWE", "currency" : "NIL", "dialCode" : "NIL", "decimal" : 2} 
]

exports.GPSMeasureDistance = function(lat1, lon1, lat2, lon2)
{
    var R = 6378.137; // Radius of earth in KM
    var dLat = parseFloat(lat2) * Math.PI / 180 - parseFloat(lat1) * Math.PI / 180;
    var dLon = parseFloat(lon2) * Math.PI / 180 - parseFloat(lon1) * Math.PI / 180;
    var a = Math.sin(dLat/2) * Math.sin(dLat/2) +
    Math.cos(parseFloat(lat1) * Math.PI / 180) * Math.cos(parseFloat(lat2) * Math.PI / 180) *
    Math.sin(dLon/2) * Math.sin(dLon/2);
    var c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
    var d = R * c;
    return d * 1000; // meters
}

exports.map_range = function(value, low1, high1, low2, high2)
{
    return low2 + (high2 - low2) * (value - low1) / (high1 - low1);
}

exports.getFareZone = function(estimatedDuration,zoneFare,zoneTimeBlock)
{
  var blockCount = parseInt((estimatedDuration / zoneTimeBlock)) ; //block count must be in interger...
  var blockBalance = (parseInt((estimatedDuration % zoneTimeBlock)) > 0) ? zoneFare : 0 ; //Remainder of block...
  var fare = (blockCount * zoneFare) + blockBalance; // fare is accordingly....based on block charge.

  return({"status":"OK" , "fareInCents":fare});
}

exports.arrayRemoveItem = function(_arrItem,_arrNum)
{
  return _arrItem.slice(0, _arrNum-1).concat(_arrItem.slice(_arrNum, _arrItem.length))
}

exports.getCountryObjects = function()
{
  return countryArr;
}